# This is a basic workflow to help you get started with Actions

name: Build Android

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Create Env
        run: touch .env
      - name: Set Env
        run: echo "MODE=DEV\nRADAR_API_KEY=REPLACE_ME\nTENANT=178a51bf-8b20-49ff-b655-56245d5c173c" > .env

      - name: Setup Node and Yarn
        uses: mskelton/setup-yarn@v1.2.1

      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew && cd ..

      - name: Generate APK
        run: cd android && ./gradlew assembleDebug --no-daemon && cd ..
