name: Welcome to the team! 🍞😄🖥️

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "### Welcome to TTU GDSC\nSince this is your first issue, we'll share some important information for you to read before you get started:\n1. Make sure to read our [contribution guidelines](https://github.com/ttugdsc/raiderride-FUBU/blob/main/.github/CONTRIBUTING.md)\n2. By contributing, you agree to follow all [TTU GDSC and Google Community Guidelines](https://developers.google.com/community-guidelines)\nA maintainer will be looking at your issue and will comment shortly with any feedback, so keep your eyes peeled and happy coding 🎉"
          pr-message: "### Hi there, thanks for opening a PR!\nSince this is your first PR, we'll go over some things real quick.\n1. Make sure your PR and code conforms to our [contributing guidelines](https://github.com/ttugdsc/raiderride-FUBU/blob/main/.github/CONTRIBUTING.md)\n2. GitHub is going to attempt to build for both Android and IOS, this might take a few minutes.\n3. Your commits will be squashed upon merging.\nOnce the checks have passed and your PR has been reviewed we'll go ahead and merge your branch into ours. Thanks again for participating!"
